### ISSUE TITLE
42S22 - 1054 - Unknown column 'status'

### ISSUE THREAD

**Issue by ifa-charlie** [directus/directus-sdk-php#33]
# Setup
MAMP: Apache/2.2.34
php7.1.12
Directus 6.4.9
PHP SDK 1.1.1? -- Installed in a separate directory with it's own composer.json
MySQL: 5.6.38

# Error:

<pre><code>
[21-Jun-2018 18:46:35 Europe/Berlin] PHP Fatal error:  Uncaught GuzzleHttp\Exception\ServerException: Server error: `GET http://mydomain.local/directus/api/1.1/tables/pages/rows?status=1&orderBy=sort&orderDirection=ASC` resulted in a `500 Internal Server Error` response:
{
  "success":false,
  "error":{
    "message":"Statement could not be executed (42S22 - 1054 - Unknown column 'status'  (truncated...)
 in /Applications/MAMP/htdocs/mydomain/data/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113
Stack trace:
#0 /Applications/MAMP/htdocs/mydomain/data/vendor/guzzlehttp/guzzle/src/Middleware.php(66): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response))
#1 /Applications/MAMP/htdocs/mydomain/data/vendor/guzzlehttp/promises/src/Promise.php(203): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response))
#2 /Applications/MAMP/htdocs/mydomain/data/vendor/guzzlehttp/promises/src/Promise.php(156): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Respons in /Applications/MAMP/htdocs/mydomain/data/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php on line 113
</code></pre>

# API Call:

<pre><code>
require 'vendor/autoload.php';
$client = \Directus\SDK\ClientFactory::create('mykey', [
  'base_url' => 'http://mydomain.local/directus/',
  'version' => '1.1'
]);

$pages = $client->getItems('pages');
foreach ($pages as $page) {
  echo $page->title . '<br>';
}</code></pre>

**Comment by ifa-charlie** [comment]
I did a little more digging and realized that the issue stemmed from my dev environment. It turns out that I needed to use the MAMP version of PHP.

<pre><code>
# Use MAMP version of PHP
PHP_VERSION=`command ls /Applications/MAMP/bin/php/ | sort -n | tail -1`
export PATH=/Applications/MAMP/bin/php/${PHP_VERSION}/bin:$PATH
</code></pre>

[https://stackoverflow.com/questions/4145667/how-to-override-the-path-of-php-to-use-the-mamp-path](https://stackoverflow.com/questions/4145667/how-to-override-the-path-of-php-to-use-the-mamp-path)

I'm very much looking forward to the Python SDK.

Thank you!
